"""add_task_position

Revision ID: b63fb48302b9
Revises: 66b1a5d4e7a0
Create Date: 2026-05-10 21:44:17.952725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63fb48302b9'
down_revision: Union[str, None] = '66b1a5d4e7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'password_entries', 'password_categories', ['category_id'], ['id'])
    op.alter_column('popcorn_entries', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('todo_tasks', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('users', 'has_seen_onboarding',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'has_seen_onboarding',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('todo_tasks', 'position')
    op.alter_column('popcorn_entries', 'rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'password_entries', type_='foreignkey')
    # ### end Alembic commands ###
